spring.application.name=VolleyballScouting
spring.thymeleaf.cache = false
spring.security.user.name=admin
spring.security.user.password=admin
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
